# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-16 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='praiserecord',
            name='standard',
            field=models.CharField(blank=True, choices=[('1', '国家级'), ('2', '省级'), ('3', '校级'), ('4', '学院级')], default='', max_length=2, verbose_name='级别'),
        ),
    ]
