# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-16 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0003_auto_20180716_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='praiserecord',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quality.Term', verbose_name='当前学期'),
        ),
        migrations.AddField(
            model_name='publishmentrecord',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quality.Term', verbose_name='当前学期'),
        ),
    ]
